import assert from 'node:assert/strict'
import test from 'node:test'
import { createPinia, setActivePinia } from 'pinia'
import { useAuthStore } from '../src/stores/auth.js'
import { LADDER_MATCH_WORKSPACE_SCHEMA_VERSION, sanitizeBulkPairingDraft, sanitizeLadderWorkspaceDocument, useLadderMatchWorkspaceStore } from '../src/stores/ladderMatchWorkspace.js'
function memoryStorage() { const values = new Map(); return { getItem: (key) => values.has(key) ? values.get(key) : null, setItem: (key, value) => values.set(String(key), String(value)), removeItem: (key) => values.delete(String(key)) } }
function freshStores(actorId = 'admin-a') { const storage = memoryStorage(); globalThis.localStorage = storage; globalThis.window = { localStorage: storage }; setActivePinia(createPinia()); const authStore = useAuthStore(); authStore.user = { id: actorId, playerId: actorId, name: 'Admin' }; authStore.isLoggedIn = true; const workspaceStore = useLadderMatchWorkspaceStore(); workspaceStore.hydrateForCurrentActor(); return { authStore, workspaceStore } }
test('workspace mode is global while draft data is isolated per ladder', () => { const { workspaceStore } = freshStores(); workspaceStore.setMode('bulk'); workspaceStore.replaceBulkDrafts({ clubId: 'greenview', ladderId: 'mens', drafts: [{ id: 'draft-1', challengerId: 'alex', opponentId: 'prince', createdAt: '2026-09-23T10:00:00.000Z' }] }); assert.equal(workspaceStore.mode, 'bulk'); assert.equal(workspaceStore.getBulkDrafts('greenview', 'mens').length, 1); assert.deepEqual(workspaceStore.getBulkDrafts('greenview', 'womens'), []) })
test('workspace persistence is isolated by authenticated actor', () => { const { authStore, workspaceStore } = freshStores('admin-a'); workspaceStore.setMode('bulk'); workspaceStore.replaceBulkDrafts({ clubId: 'greenview', ladderId: 'mens', drafts: [{ id: 'draft-a', challengerId: 'alex', opponentId: 'prince' }] }); authStore.user = { id: 'admin-b' }; workspaceStore.hydrateForCurrentActor(); assert.equal(workspaceStore.mode, 'individual'); authStore.user = { id: 'admin-a' }; workspaceStore.hydrateForCurrentActor(); assert.equal(workspaceStore.mode, 'bulk') })
test('stored workspace input is bounded and malformed pairings are discarded', () => { assert.equal(sanitizeBulkPairingDraft({ id: 'same', challengerId: 'alex', opponentId: 'alex' }), null); const document = sanitizeLadderWorkspaceDocument({ schemaVersion: LADDER_MATCH_WORKSPACE_SCHEMA_VERSION, mode: 'bulk', clubs: { greenview: { ladders: { mens: { bulk: { drafts: [{ id: 'valid', challengerId: 'alex', opponentId: 'prince' }, { id: '', challengerId: 'bad', opponentId: 'data' }] } } } } } }); assert.equal(document.clubs.greenview.ladders.mens.bulk.drafts.length, 1) })
test('unknown schema versions are never trusted', () => { const document = sanitizeLadderWorkspaceDocument({ schemaVersion: 999, mode: 'bulk', clubs: { greenview: {} } }); assert.equal(document.mode, 'individual'); assert.deepEqual(document.clubs, {}) })