import { LADDER_ENTRY_STATUSES, normalizeLadderEntries } from './ladderWorkspace.js'
import { collectClubMembers } from '../utils/club/memberData.js'

function cleanId(value) { return String(value || '').trim().slice(0, 120) }
function participantId(player) { return cleanId(player?.playerId || player?.id) }

export function ladderRosterFromSetup({ setup, ladderId } = {}) {
  const requestedLadderId = cleanId(ladderId)
  const ladder = (Array.isArray(setup?.ladders) ? setup.ladders : []).find((item) => cleanId(item?.id) === requestedLadderId) || null
  if (!ladder) return { ladder: null, roster: [], memberIds: new Set() }
  const membersById = new Map(collectClubMembers(setup).map((member) => [cleanId(member.id), member]))
  const roster = normalizeLadderEntries(ladder.entries).filter((entry) => entry.status === LADDER_ENTRY_STATUSES.ACTIVE && Number.isInteger(Number(entry.position)) && Number(entry.position) >= 1).sort((a, b) => Number(a.position) - Number(b.position)).map((entry) => { const member = membersById.get(cleanId(entry.memberId)); return member ? { ...member, id: cleanId(member.id), name: member.name || 'Club member', imageUrl: member.photoUrl || member.imageUrl || '', rank: Number(entry.position), ladderRank: Number(entry.position), ladderId: requestedLadderId, ladderEntryStatus: entry.status } : null }).filter(Boolean)
  return { ladder, roster, memberIds: new Set(roster.map((player) => cleanId(player.id))) }
}
export function ladderParticipant({ setup, ladderId, playerId } = {}) { return ladderRosterFromSetup({ setup, ladderId }).roster.find((player) => cleanId(player.id) === cleanId(playerId)) || null }
export function tournamentCategoryParticipantIds(category) { const ids = new Set(); const add = (p) => { if (!p?.isBye) { const id = participantId(p); if (id) ids.add(id) } }; (Array.isArray(category?.players) ? category.players : []).forEach(add); (Array.isArray(category?.groups) ? category.groups : []).forEach((g) => (Array.isArray(g?.players) ? g.players : []).forEach(add)); return ids }
export function tournamentGroupParticipantIds(category, groupId) { const group = (Array.isArray(category?.groups) ? category.groups : []).find((g) => cleanId(g?.id) === cleanId(groupId)); const ids = new Set(); (Array.isArray(group?.players) ? group.players : []).forEach((p) => { if (!p?.isBye) { const id = participantId(p); if (id) ids.add(id) } }); return ids }
export function tournamentMatchScopeIssue({ match, tournament, expectedClubId = '', expectedTournamentId = '', expectedCategoryId = '' } = {}) { if (!match || String(match.type || match.source || '').toLowerCase() !== 'tournament') return 'This is not a Tournament match.'; const tournamentId = cleanId(match.tournamentId); const categoryId = cleanId(match.categoryId); if (expectedTournamentId && tournamentId !== cleanId(expectedTournamentId)) return 'This Match belongs to a different Tournament.'; if (!tournament || cleanId(tournament.id) !== tournamentId) return 'The Tournament for this Match could not be found.'; if (expectedClubId && tournament.clubId && cleanId(tournament.clubId) !== cleanId(expectedClubId)) return 'This Tournament does not belong to the active club.'; const category = (Array.isArray(tournament.categories) ? tournament.categories : []).find((item) => cleanId(item?.id) === categoryId) || null; if (!category) return 'This Match does not belong to a valid Tournament category.'; if (expectedCategoryId && categoryId !== cleanId(expectedCategoryId)) return 'This Match belongs to a different Tournament category.'; const ids = tournamentCategoryParticipantIds(category); const p1 = cleanId(match.player1Id); const p2 = cleanId(match.player2Id); if (!p1 || !p2 || !ids.has(p1) || !ids.has(p2)) return 'Both Tournament players must belong to this category.'; if (match.groupId) { const groupIds = tournamentGroupParticipantIds(category, match.groupId); if (!groupIds.has(p1) || !groupIds.has(p2)) return 'Both Tournament players must belong to this group.' }; return '' }