import { computed, ref, watch } from 'vue'
import { defineStore } from 'pinia'
import { useAuthStore } from './auth.js'
export const LADDER_MATCH_WORKSPACE_SCHEMA_VERSION = 1
const P='gorra.ladder-match-workspace.v1', M=new Set(['individual','bulk']), B=new Set(['__proto__','prototype','constructor'])
const id=(v,n=160)=>{v=String(v||'').trim();return !v||v.length>n||B.has(v)?'':v}
const stamp=v=>{v=String(v||'').trim();if(!v||v.length>64)return '';const d=Date.parse(v);return Number.isFinite(d)?new Date(d).toISOString():''}
const empty=()=>({individual:{selectedPlayerId:''},bulk:{drafts:[]},updatedAt:''})
export function sanitizeBulkPairingDraft(v){const a=id(v?.id,200),c=id(v?.challengerId),o=id(v?.opponentId);return !a||!c||!o||c===o?null:{id:a,challengerId:c,opponentId:o,createdAt:stamp(v?.createdAt)}}
const drafts=v=>{if(!Array.isArray(v))return [];const seen=new Set(),out=[];for(const x of v){if(out.length>=64)break;const d=sanitizeBulkPairingDraft(x);if(d&&!seen.has(d.id)){seen.add(d.id);out.push(d)}}return out}
const workspace=v=>({individual:{selectedPlayerId:id(v?.individual?.selectedPlayerId)},bulk:{drafts:drafts(v?.bulk?.drafts)},updatedAt:stamp(v?.updatedAt)})
const clubs=v=>{if(!v||typeof v!=='object'||Array.isArray(v))return {};const out={};let c=0;for(const[k,x]of Object.entries(v)){if(c++>=40)break;const ck=id(k),ls=x?.ladders;if(!ck||!ls||typeof ls!=='object'||Array.isArray(ls))continue;const ladders={};let l=0;for(const[lk,w]of Object.entries(ls)){if(l++>=100)break;const key=id(lk);if(key)ladders[key]=workspace(w)}out[ck]={ladders}}return out}
export function sanitizeLadderWorkspaceDocument(v){if(!v||typeof v!=='object'||Array.isArray(v)||Number(v.schemaVersion)!==1)return{schemaVersion:1,mode:'individual',clubs:{},updatedAt:''};return{schemaVersion:1,mode:M.has(v.mode)?v.mode:'individual',clubs:clubs(v.clubs),updatedAt:stamp(v.updatedAt)}}
const key=a=>{a=id(a);return a?`${P}:${encodeURIComponent(a)}`:''}, scope=(c,l)=>({clubId:id(c),ladderId:id(l)})
export const useLadderMatchWorkspaceStore=defineStore('ladderMatchWorkspace',()=>{const auth=useAuthStore(),mode=ref('individual'),data=ref({}),updatedAt=ref(''),hydrated=ref(''),actorId=computed(()=>id(auth.user?.id||auth.user?.playerId||''))
const reset=()=>{mode.value='individual';data.value={};updatedAt.value=''}, persist=()=>{const k=key(actorId.value);if(!k||typeof window==='undefined'||!window.localStorage)return false;try{window.localStorage.setItem(k,JSON.stringify({schemaVersion:1,mode:mode.value,clubs:data.value,updatedAt:updatedAt.value}));return true}catch{return false}}
function hydrateForCurrentActor(){reset();hydrated.value=actorId.value;const k=key(actorId.value);if(!k||typeof window==='undefined'||!window.localStorage)return;try{const raw=window.localStorage.getItem(k);if(!raw)return;const d=sanitizeLadderWorkspaceDocument(JSON.parse(raw));mode.value=d.mode;data.value=d.clubs;updatedAt.value=d.updatedAt}catch{reset()}}
function getLadderWorkspace(c,l){const s=scope(c,l);return!s.clubId||!s.ladderId?empty():workspace(data.value[s.clubId]?.ladders?.[s.ladderId]||empty())}
function write(c,l,w){const s=scope(c,l);if(!s.clubId||!s.ladderId)return false;const now=new Date().toISOString(),club=data.value[s.clubId]||{ladders:{}};data.value={...data.value,[s.clubId]:{...club,ladders:{...(club.ladders||{}),[s.ladderId]:workspace({...w,updatedAt:now})}}};updatedAt.value=now;persist();return true}
function setMode(v){v=M.has(v)?v:'individual';if(mode.value!==v){mode.value=v;updatedAt.value=new Date().toISOString();persist()}}
const getIndividualDraft=(c,l)=>({...getLadderWorkspace(c,l).individual}), setIndividualSelectedPlayer=({clubId,ladderId,playerId})=>{const w=getLadderWorkspace(clubId,ladderId);return write(clubId,ladderId,{...w,individual:{...w.individual,selectedPlayerId:id(playerId)}})}, clearIndividualDraft=(c,l)=>{const w=getLadderWorkspace(c,l);return write(c,l,{...w,individual:{selectedPlayerId:''}})}
const getBulkDrafts=(c,l)=>getLadderWorkspace(c,l).bulk.drafts.map(d=>({...d})),replaceBulkDrafts=({clubId,ladderId,drafts:x})=>{const w=getLadderWorkspace(clubId,ladderId);return write(clubId,ladderId,{...w,bulk:{drafts:drafts(x)}})},removeBulkDraft=({clubId,ladderId,draftId})=>{draftId=id(draftId,200);return draftId?replaceBulkDrafts({clubId,ladderId,drafts:getBulkDrafts(clubId,ladderId).filter(d=>d.id!==draftId)}):false}
function clearBulkDrafts(c,l){return replaceBulkDrafts({clubId:c,ladderId:l,drafts:[]})} function clearLadderWorkspace(c,l){const s=scope(c,l),club=data.value[s.clubId];if(!s.clubId||!s.ladderId)return false;if(!club?.ladders?.[s.ladderId])return true;const ladders={...club.ladders};delete ladders[s.ladderId];data.value={...data.value,[s.clubId]:{...club,ladders}};updatedAt.value=new Date().toISOString();persist();return true}
function exportLadderSnapshot(c,l){const s=scope(c,l);if(!s.clubId||!s.ladderId)return null;const w=getLadderWorkspace(c,l);return{schemaVersion:1,clubId:s.clubId,ladderId:s.ladderId,individual:{...w.individual},bulk:{drafts:w.bulk.drafts.map(d=>({...d}))},updatedAt:w.updatedAt||updatedAt.value||''}} function clearCurrentActorWorkspace(){const k=key(actorId.value);reset();try{if(k&&typeof window!=='undefined')window.localStorage.removeItem(k)}catch{}}
watch(actorId,a=>{if(a!==hydrated.value)hydrateForCurrentActor()},{immediate:true});return{mode,actorId,updatedAt,setMode,hydrateForCurrentActor,getLadderWorkspace,getIndividualDraft,setIndividualSelectedPlayer,clearIndividualDraft,getBulkDrafts,replaceBulkDrafts,removeBulkDraft,clearBulkDrafts,clearLadderWorkspace,exportLadderSnapshot,clearCurrentActorWorkspace}})